# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: 127.0.0.1
    port: 25
    domain: easyproject.cz
    authentication: :none
    #user_name: redmine@example.net
    #password: redmine
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: 127.0.0.1
    port: 25
    domain: easyproject.cz
    authentication: :none
    #user_name: redmine@example.net
    #password: redmine
